

def abort(error_msg):
    print(error_msg)
    exit(1)
